service: deserialise

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

functions:
  deserialise:
    handler: handler.deserialise
    url: true
    environment:
      IDL_FUNCTION_URL: ${ssm:idl_function_url}
